### ISSUE TITLE
How to set the 'eval_dict' during rendering

### ISSUE THREAD

**Issue by XuM007** [Wanggcong/SparseNeRF#10]
I tried to use my own dataset. I took 25 images with a chair and use COLMAP and LLFF's code to make it in LLFF's format. There are parameters 'near' and 'far' in the 'poses_bounds.npy'.
1.You mentioned that we should carefully set 'config.near' and 'config.far'. Are they the ones I got from 'poses_bounds.npy'? If not, how should I set them.
2.I make my dataset as LLFF format, so I just use the codes for 'LLFF'. However, I noticed in 'render.py' line 77, there is a 'eval_dict'. You have mentioned the meaning of the dict, but how should I set it for my dataset. 
My rendering results are really bad, so I wonder what is the problem. And I didn't change the windows, as there are many object in my images. These image are forward-view.
3.I wonder if it is possible to reconstruction a square room from 4 views i.e. 4 cameras from room corners. While there is few overlap between images, is it still possible to reconstruction? My test is still bad, but I want to know some possible reasons.

**Comment by Wanggcong** [comment]
Since there are no further questions, I closed this issue. You might re-open it or raise a new issue.
