### ISSUE TITLE
What is the 'superpixel' when calculating the depth loss

### ISSUE THREAD

**Issue by Red-Fairy** [Wanggcong/SparseNeRF#11]
Thanks for your brilliant paper and generous code release. I'm wondering what is the 'superpixel' when calculating the depth loss. Besides, does the depth loss involves all the pixel pairs in a 8*8 local patch (I find the patch_size in the config file is 8). 

Thanks in advance!

**Comment by Wanggcong** [comment]
Thank you for your question.   The 'superpixel' variable is not available anymore. At the very beginning, I tried to use the superpixel algorithm to help few-shot NeRF. But I am not sure if I re-use this term for other variables. Could you please let me know where is the superpixel'?

**Comment by Red-Fairy** [comment]
Thanks for your quick response. Variable 'rays_per_superpixels' exists on Line 141 of file train_kinect.py, and Line 140 of file train_iphone.py

**Comment by Wanggcong** [comment]
Thank you. I have removed it. The rays_per_superpixels is an old variable. We use 4 because we sample two pairs of points to compute depth losses (depth ranking and continuity losses).

**Comment by Red-Fairy** [comment]
Thanks for your response!
