### ISSUE TITLE
Questions about the ranking loss

### ISSUE THREAD

**Issue by JerryPW** [Wanggcong/SparseNeRF#12]
Hi! Thanks for your great job! 

However, I'm not quite sure where the ranking loss has been implemented in your code. Is the line 129 in train_llff_dtu.py ? If so, how does this depth loss compatible with the ranking loss illustrated in your essay, and how does the gt_depth information help with the the depth_loss, since ```distance_mean``` seems only comes from rendering. 

Hoping for your reply soon!

**Comment by Wanggcong** [comment]
Please check [the loss](https://github.com/Wanggcong/SparseNeRF/blob/bd95dde7fe1570ddc498a116871ac9a0ebcacd7e/train_llff_dtu.py#L178C1-L192C66) and [the ray sampling](https://github.com/Wanggcong/SparseNeRF/blob/bd95dde7fe1570ddc498a116871ac9a0ebcacd7e/internal/datasets_depth_llff_dtu.py#L511C1-L606C99). These places are the main code to implement the depth loss.

**Comment by Wanggcong** [comment]
I closed the issue since there is no further question. You might re-open the issue or raise a new issue if necessary.
