### ISSUE TITLE
Some TPU and bound error

### ISSUE THREAD

**Issue by fasogbon** [Wanggcong/SparseNeRF#15]
Hello, thank you very much for the work.

do you have any suggestion why i am having this error, it doesnt make sense to me. 
```

I1009 04:44:23.629094 140517064905856 tpu_client.py:54] Starting the local TPU driver.
I1009 04:44:23.629349 140517064905856 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I1009 04:44:23.698289 140517064905856 xla_bridge.py:231] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
/home/peter/anaconda3/envs/sparsenerf/lib/python3.6/site-packages/jax/lib/xla_bridge.py:374: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  "jax.host_id has been renamed to jax.process_index. This alias "
/home/peter/anaconda3/envs/sparsenerf/lib/python3.6/site-packages/jax/lib/xla_bridge.py:387: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  "jax.host_count has been renamed to jax.process_count. This alias "
Using following batch size 128
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/sparsenerf/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/peter/Desktop/Research/SparseNeRF2/internal/datasets_depth_kinect.py", line 549, in run
    self.queue.put(next_func())
  File "/home/peter/Desktop/Research/SparseNeRF2/internal/datasets_depth_kinect.py", line 752, in _next_train_mask
    return_dict['rgb'] = self.images[idxs][image_index][ray_indices]
IndexError: index 436106 is out of bounds for axis 0 with size 230400

```

**Comment by fasogbon** [comment]
Indeed training `train_kinect.sh `and `train_zed.sh `with your dataset is giving "out of bound error" but training with `train_iphone.sh` seems to work well. Please, any idea what might be wrong?

**Comment by Wanggcong** [comment]
Thanks. As shown in return_dict['rgb'] = self.images[idxs][image_index][ray_indices], it seems that the rays_indices are out of bound. I guess you use error scale of images. For example, in llff.gin, we use Config.factor = 8 . That means we downsample the images by a factor 8. I am not sure if it is correct without more infomation.

**Comment by fasogbon** [comment]
Are you sure you didnt have thesame error [dataset](https://drive.google.com/drive/folders/1gDVZomm0AGpgIja19Lbg4oJQmvHB30rB?usp=sharing)
because I am having this problem with the dataset you provided

**Comment by fasogbon** [comment]
images_8 folder  doesnt exist in the kinect folder and using _2 and _4 gives the error

**Comment by Wanggcong** [comment]
Thank you for your feedback. I found I commented "resize depth maps" when I cleaned the code. I fixed the problem by resizing depth maps as the images. Please find the modified code in [these lines](https://github.com/Wanggcong/SparseNeRF/blob/3fa799c76c93ae0c6e678ce436bfdbc73cbc8f7a/internal/datasets_depth_kinect.py#L1046-L1050) for kinect, and [these lines](https://github.com/Wanggcong/SparseNeRF/blob/7dd5453570efb3de964321aeb9caa12b99c4e0a2/internal/datasets_depth_zed.py#L1042-L1047) for zed2.

**Comment by fasogbon** [comment]
Thank you for your efforts.
your fix for zed works fine but kinect gives another error

`  File "train_kinect.py", line 352, in main
    step,
  File "train_kinect.py", line 237, in train_step
    all_depth_loss =all_depth_loss,
TypeError: __init__() got an unexpected keyword argument 'disp_mses'
`

**Comment by Wanggcong** [comment]
> Thank you for your efforts. your fix for zed works fine but kinect gives another error
> 
> ` File "train_kinect.py", line 352, in main step, File "train_kinect.py", line 237, in train_step all_depth_loss =all_depth_loss, TypeError: __init__() got an unexpected keyword argument 'disp_mses'`

I copied the code and ran it. I did not find this error. Did it rise at the very beginning or after some iterations?

**Comment by fasogbon** [comment]
It is at the beginning after printing the batch sizes. Can it be that the Kinect version  is using some TensorFlow (cuda) related for the depth? Whereas zed and iPhone isn’t using?

**Comment by Wanggcong** [comment]
I don't think so. We only use depth maps of Kinect. So it would not be the Kinect version problem.

**Comment by fasogbon** [comment]
All problem solved now. It turns out i was copying your old kinect code whic have the train stats that does not define "disp_mses". Thank you for all your help.

**Comment by Wanggcong** [comment]
Thank you.
