### ISSUE TITLE
Any idea to run the code in the blender dataset?

### ISSUE THREAD

**Issue by JunyuanDeng** [Wanggcong/SparseNeRF#17]
Thanks for your excellent job!

Do you know any ways to test your code in the blender dataset?

Thanks in advance!

**Comment by Wanggcong** [comment]
Please try to implement the blender dataset according to this [link](https://github.com/Wanggcong/SparseNeRF/blob/main/tutorial/tutorial.md)

**Comment by Wanggcong** [comment]
Since there are no further questions, I closed the issue. You might re-open it if necessary.
