### ISSUE TITLE
Not able to run custom data

### ISSUE THREAD

**Issue by sairisheek** [Wanggcong/SparseNeRF#20]
Hello, thanks for the great work. I am trying to run mipnerf scenes with ablated views, but for some reason the training renderings look something like this 
![image](https://github.com/Wanggcong/SparseNeRF/assets/6778535/d343b8f4-00d5-4372-aa06-d997144084c0)
Any idea why this would be the case? Seems like PSNR is high while training, but extremely low in test (the test set and train set are the same images).

**Comment by perf-project** [comment]
Thanks for your question. NeRF is able to interpolate the views, but could be hard to extrapolate views. For example, you use view 1, view 3, view 5 for training while use view 2 and view 4 for testing. If you use view 2,3,4 for training and view 1,5 for testing, it could lead to a bad result.

**Comment by Wanggcong** [comment]
Thanks for your question. NeRF is able to interpolate the views, but could be hard to extrapolate views. For example, you use view 1, view 3, view 5 for training while use view 2 and view 4 for testing. If you use view 2,3,4 for training and view 1,5 for testing, it could lead to a bad result.

Moreover, these training views should be overlapped to some extent.

**Comment by sairisheek** [comment]
I believe the testing and training views are the same. I think it's caused the by the random rays flag being set to false when evaluating.

**Comment by Wanggcong** [comment]
Can you show the rendered video?

**Comment by sairisheek** [comment]
Yes, I'll try to get that for you. Meanwhile I had fixed some bugs with our camera poses and am getting results like this for a 360 scene. 
![image](https://github.com/Wanggcong/SparseNeRF/assets/6778535/89673a5b-2bf7-4c3f-984c-16a570c178d7)
I had set remap_to_hemisphere to true so as to not use NDC. Is there something I'm missing?

**Comment by Wanggcong** [comment]
Yes, 360-degree is different from NDC. You might carefully handle this problem. Do you directly use our code for 360-degree scenes?

**Comment by Wanggcong** [comment]
I closed this issue since there are no further questions. You might re-open it or raise a new issue if necessary.
