### ISSUE TITLE
how to train on 6 views and 9 views?

### ISSUE THREAD

**Issue by 52Hert-Z** [Wanggcong/SparseNeRF#21]
I train 6 views and 9 views only change the inputviews in the gin file, and get lower metrics than FreeNeRF, how could I train on 6 views and 9 views?

**Comment by Wanggcong** [comment]
> I train 3 views based on your gin file, and get the lower SSIM (0.625) & LPIPS (0.328) than the results in the paper (SSIM 0.714 & LPIPS 0.243), Is there something wrong with my settings?

Hi, I knew your problem. Please use our [updated arkiv result](https://arxiv.org/abs/2303.16196v2). The problem might be the some unaligned evaluations. SSIM (0.625) & LPIPS (0.328) is an aligned evaluation.

**Comment by Wanggcong** [comment]
There are no further responds. I closed this issue. If you have any other questions, you can re-open it or raise a new issue.
