### ISSUE TITLE
Hello, I have encountered some issues while using SpareNeRF and Free+SpareNeRF.

### ISSUE THREAD

**Issue by myself-oriented** [Wanggcong/SparseNeRF#23]
Hello, thank you for sharing the code. I converted my data into LLFF format and encountered issues while experimenting with SparseNeRF and Free+SparseNeRF. When predicting a target view with four input views, FreeNeRF performs well with minor changes to 'split_indices = { 'test': [2],  'train': [0, 1, 3, 4],},' achieving a PSNR of approximately 21 dB. However, SparseNeRF seems ineffective, yielding a PSNR of around 10 dB. I've attempted various adjustments, such as modifying 'near' and 'far,' (0.1:1, 2:10)changing sampling block size,(30*30,60*60,h*w) and adjusting batch size(512,1024,4096), but with limited success. Similar issues arise with FreeNeRF+SparseNeRF. Are there other key parameters to consider? Additionally, when testing on the 'room' subset of the LLFF dataset with only 20 retained views (originally 41 views), the results are suboptimal (around 10 dB), whereas FreeNeRF performs well. Any insights into this discrepancy?

**Comment by myself-oriented** [comment]
Adding a note, training SparseNeRF works well with the complete 'room' data from LLFF. However, even with a custom LLFF dataset expanded to 16 views, SparseNeRF still yields suboptimal results (around 10 dB), while the native NeRF produces outputs surpassing 20 dB. I suspect there might be an issue with certain parameters in the code. Any suggestions?

**Comment by Wanggcong** [comment]
It is weird that SparseNeRF achieves 10db for 4 views. I tested 4-views before, but not this result. It might be some bugs.

**Comment by myself-oriented** [comment]
Thank you for your response. I tested with FreeNeRF under the same settings and obtained results of 20 dB. However, despite expanding the views to 16, SparseNeRF still shows no improvement. In your opinion, which parameters might need modification?

**Comment by myself-oriented** [comment]
Thank you for your response. It seems I have resolved the issue by adjusting 'near' and 'far' in the gin file, and disabling 'anneal_nearfar.' This resulted in an SSIM of approximately 0.89.

**Comment by Wanggcong** [comment]
Thank you for your responses. Since there is no further question. I closed this issue. You might re-open it or raise a new issue if any questions.
