### ISSUE TITLE
About Depth Loss

### ISSUE THREAD

**Issue by aiyb1314** [Wanggcong/SparseNeRF#27]
Thanks for your work, what is the implementation of the Spatial Continuity Distillation Loss k-nearest neighbor part of the paper in the code?

**Comment by Wanggcong** [comment]
Please check [this code block](https://github.com/Wanggcong/SparseNeRF/blob/6b07a7bf29803cbe4ed0ca25a2397f32ab24e62f/internal/datasets_depth_llff_dtu.py#L549-L592).

**Comment by Wanggcong** [comment]
I closed this issue since there are no further questions. You might re-open it or raise a new issue.
