### ISSUE TITLE
What's the use of `depth_mono`?

### ISSUE THREAD

**Issue by hermosaaurora** [Wanggcong/SparseNeRF#5]
I'm a little confused about the `depth_mono` variable here:

https://github.com/Wanggcong/SparseNeRF/blob/01512b4534340d41e3ac90ed6dc0aa72902ae5a4/internal/datasets_depth_llff_dtu.py#L596-L649

It seems that `depth_mono` is not used or saved to return_dict, so what's its use? I believe the `ray_indices` list has already taken the rank/order into consideration.

**Comment by Wanggcong** [comment]
Thank you for your comment. Yes, it is useless. I will clean it.

**Comment by Wanggcong** [comment]
I have fixed the issue and closed the issue. If you have any question, you might re-open or raise a new one.
