### ISSUE TITLE
A question about `distance_mean`

### ISSUE THREAD

**Issue by hermosaaurora** [Wanggcong/SparseNeRF#9]
hi, I'm wondering here `distance_mean` is distance (Euclidian distance from the optical center of the camera to the 3d point in the scene) or z depth (from the optical center of the camera to the image plane)?

https://github.com/Wanggcong/SparseNeRF/blob/dd5f39176068274f4dc4da2e270484273390da97/internal/mip.py#L259-L266

**Comment by hermosaaurora** [comment]
to my understanding, I guess it is z depth right?

https://github.com/Wanggcong/SparseNeRF/blob/dd5f39176068274f4dc4da2e270484273390da97/internal/mip.py#L195-L208

because only when it is z depth, you should multiply `dists` with direction norm then.

**Comment by Wanggcong** [comment]
I think it depends on if you use NDC. If yes, it should be z depth. Othersies, it could be the Euclidian distance from the optical center of the camera to the 3d point in the scene. Correct me if I make mistates.

**Comment by hermosaaurora** [comment]
I agree with you when it uses NDC space warping. But I have not investigated into the non-NDC part yet, so I'm not sure about that. I think maybe I should also refer to mip-nerf repo, since there are some helpful discussions.

Another question is about how to transform the distance in NDC space to z depth in the camera world. I tried to do this today in the following steps:

1. transform $t'$ (`rendering["distance_mean"]` in your code) to $t$ according to equation 15. (supplementary materials of NeRF paper):

<img width="822" alt="image" src="https://github.com/Wanggcong/SparseNeRF/assets/142530595/89f3a685-e696-476c-afa7-33ab8ba5ebd1">

2. add $t_n$ to $t$ because the code applies shift to ray origins from the camera optical center to the near plane's intersection point with the ray.

<img width="814" alt="image" src="https://github.com/Wanggcong/SparseNeRF/assets/142530595/afb030ab-bcf7-4297-8f7b-318daea77977">

and $t_n$ is here: 

https://github.com/Wanggcong/SparseNeRF/blob/dd5f39176068274f4dc4da2e270484273390da97/internal/datasets_depth_llff_dtu.py#L81-L82

**Comment by Wanggcong** [comment]
Sure, you might carefully derive an equation from these equations. Another way could be training in the non-NDC space and it might be easy to transform distances to z depth.

**Comment by Wanggcong** [comment]
I closed this issue. If you have any questions, you might raise a new issue or re-open the issue.
